apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness-v2
  labels:
    env: prod
    creation_method: manual
spec:
  containers:
  - name: kubia
    image: luksa/kubia
    livenessProbe:
      httpGet:
        path: /blabla
        port: 8080
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
