apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    app: nginx-with-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      key: nginx-with-secret
  template:
    metadata:
      labels:
        key: nginx-with-secret
    spec:
      containers:
        - name: nginx
          image: nginx
          env:
            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nginx-secret
                  key: username
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nginx-secret
                  key: password
