apiVersion: v1
kind: Pod
metadata:
  name: "fortune-custom"
  namespace: default
  labels:
    app: "fortune-custom"
spec:
  containers:
  - name: fortune-custom
    image: fortune-custom-build:latest
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
    - name: INTERVAL
      valueFrom:
        configMapKeyRef:
          name: fortune-config
          key: sleep-interval
    args: ["$(INTERVAL)"]