version: "3.8"

services:
  rancher:
    image: rancher/rancher
    container_name: rancher
    privileged: true
    restart: unless-stopped
    ports:
      - "8080:80"
      - "4430:443"
      - "6444:6444"
    volumes:
      - rancher_data:/var/lib/rancher

volumes:
  rancher_data:
    driver: local