get_services:
kubectl get services 

exec_command:
kubectl exec pod_name -- <command_to_exec>

get_environment:
kubectl exec <pod_name> -- <command>


get_details_of_service:
kubectl describe svc <service_name>

get_endpoint_of_sevice:
kubectl get endpoints <service_name>