apiVersion: v1
kind: Service
metadata:
  name: kubia-sticky-session
  namespace: replicaset-example
spec:
  selector:
    app: kubia
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - port: 80
    targetPort: 8080
