apiVersion: v1
kind: Service
metadata:
  name: kubia-nodeport
  namespace: replicaset-example
spec:
  selector:
    app: kubia
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80  # Service port (ClusterIP)
    targetPort: 8080 # Container port inside the Pod
    nodePort: 30001  # External port on the Node (range: 30000–32767)