apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubiareplicaset
  namespace: replicaset-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia
          image: luksa/kubia
